const products=[
{id:1,name:'Montre connectée Pro',cat:'electronics',store:'Tech Kpalimé',price:45000,img:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=85',rating:'4.8',tag:'Tendance'},
{id:2,name:'Smartphone nouvelle génération',cat:'electronics',store:'Tech Kpalimé',price:185000,img:'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=85',rating:'4.7',tag:'Nouveau'},
{id:3,name:'Ordinateur portable Pro',cat:'computing',store:'Digital House',price:395000,img:'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&q=85',rating:'4.9',tag:'Pro'},
{id:4,name:'Casque audio sans fil',cat:'electronics',store:'Tech Kpalimé',price:35000,img:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=85',rating:'4.6',tag:''},
{id:5,name:'Fauteuil moderne',cat:'home',store:'Maison & Ambiance',price:120000,img:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=85',rating:'4.8',tag:'Maison'},
{id:6,name:'Sneakers tendance',cat:'fashion',store:'Style Togo',price:28000,img:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=85',rating:'4.7',tag:'Populaire'},
{id:7,name:'Terrain résidentiel',cat:'realestate',store:'Togo Immo',price:0,img:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=85',rating:'4.5',tag:'Immobilier'},
{id:8,name:'TV Smart 55 pouces',cat:'electronics',store:'Tech Kpalimé',price:285000,img:'https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=85',rating:'4.7',tag:''}
];
let current=products.slice(),cart=JSON.parse(localStorage.getItem('tm_cart')||'[]');
const money=n=>n?new Intl.NumberFormat('fr-FR').format(n)+' F CFA':'Prix sur demande';
const grid=document.getElementById('productGrid');
function renderProducts(){grid.innerHTML=current.map(p=>`<article class="product"><div class="product-img"><img src="${p.img}" alt="${p.name}" loading="lazy">${p.tag?`<span class="tag">${p.tag}</span>`:''}<button class="heart" aria-label="Favori">♡</button></div><div class="product-body"><span class="product-store">${p.store}</span><h3>${p.name}</h3><div class="rating">★★★★★ <span>${p.rating}</span></div><div class="price">${money(p.price)}</div><div class="product-bottom"><button class="add" onclick="addToCart(${p.id})">Ajouter</button><button class="buy" onclick="buyNow(${p.id})">Commander</button></div></div></article>`).join('');}
function addToCart(id){const p=products.find(x=>x.id===id),found=cart.find(x=>x.id===id);if(found)found.qty++;else cart.push({...p,qty:1});saveCart();openCart();}
function buyNow(id){addToCart(id);}
function saveCart(){localStorage.setItem('tm_cart',JSON.stringify(cart));document.getElementById('cartCount').textContent=cart.reduce((s,x)=>s+x.qty,0);renderCart();}
function renderCart(){const el=document.getElementById('cartItems');if(!cart.length){el.innerHTML='<div style="text-align:center;color:#7b8999;padding:50px 10px">Votre panier est vide.<br>Ajoutez quelques produits pour commencer.</div>';document.getElementById('cartTotal').textContent='0 F CFA';return}el.innerHTML=cart.map(x=>`<div class="cart-item"><img src="${x.img}" alt=""><div><b>${x.name}</b><small>${x.qty} × ${money(x.price)}</small></div><button onclick="removeItem(${x.id})">Supprimer</button></div>`).join('');document.getElementById('cartTotal').textContent=money(cart.reduce((s,x)=>s+(x.price*x.qty),0));}
function removeItem(id){cart=cart.filter(x=>x.id!==id);saveCart();}
function openCart(){document.getElementById('cart').classList.add('open');document.getElementById('overlay').classList.add('show');}
function closeCart(){document.getElementById('cart').classList.remove('open');document.getElementById('overlay').classList.remove('show');}
function search(){const q=document.getElementById('searchInput').value.toLowerCase().trim(),cat=document.getElementById('searchCat').value;current=products.filter(p=>(cat==='all'||p.cat===cat)&&(p.name.toLowerCase().includes(q)||p.store.toLowerCase().includes(q)));renderProducts();document.getElementById('produits').scrollIntoView({behavior:'smooth'});}
document.getElementById('searchBtn').onclick=search;document.getElementById('searchInput').addEventListener('keydown',e=>{if(e.key==='Enter')search()});document.querySelectorAll('.cat').forEach(b=>b.onclick=()=>{document.getElementById('searchCat').value=b.dataset.cat;document.getElementById('searchInput').value='';search()});document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');current=products.slice();if(b.dataset.sort==='priceAsc')current.sort((a,b)=>a.price-b.price);if(b.dataset.sort==='priceDesc')current.sort((a,b)=>b.price-a.price);renderProducts()});
document.getElementById('cartBtn').onclick=openCart;document.getElementById('closeCart').onclick=closeCart;document.getElementById('overlay').onclick=closeCart;document.getElementById('orderBtn').onclick=()=>{if(!cart.length)return alert('Votre panier est vide.');const lines=cart.map(x=>`• ${x.name} × ${x.qty} — ${money(x.price*x.qty)}`).join('%0A');const total=money(cart.reduce((s,x)=>s+x.price*x.qty,0));window.open(`https://wa.me/22896894394?text=${encodeURIComponent('Bonjour TOGO MARKET, je souhaite commander :\n')}${lines}%0A%0ATotal : ${encodeURIComponent(total)}`,'_blank')};
const modal=document.getElementById('modal');function openModal(){modal.classList.add('open')}function closeModal(){modal.classList.remove('open')}document.getElementById('sellBtn').onclick=openModal;document.getElementById('sellHero').onclick=openModal;document.getElementById('ctaSell').onclick=openModal;document.getElementById('modalClose').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};document.getElementById('shopSubmit').onclick=()=>{const n=document.getElementById('shopName').value.trim()||'ma boutique';const msg=`Bonjour, je souhaite ouvrir la boutique « ${n} » sur TOGO MARKET.`;window.open(`https://wa.me/22896894394?text=${encodeURIComponent(msg)}`,'_blank')};
document.getElementById('accountBtn').onclick=()=>alert('L’espace compte client sera connecté à la prochaine étape avec une base de données.');document.getElementById('locationBtn').onclick=()=>alert('Zone de livraison sélectionnée : Lomé. La sélection de ville sera ajoutée avec le système de comptes et de livraison.');
renderProducts();saveCart();
